FROM alpine:3.20

WORKDIR /app

ARG TARGETARCH
ARG BINARY_SOURCE_DIR=dist

RUN apk add --no-cache ca-certificates tzdata && \
    addgroup -S app && \
    adduser -S app -G app && \
    mkdir -p /data && \
    chown -R app:app /app /data

COPY ${BINARY_SOURCE_DIR}/portlyn-nodeagent-linux-${TARGETARCH} /app/nodeagent
RUN chmod +x /app/nodeagent

USER app

ENV XDG_CONFIG_HOME=/data

ENTRYPOINT ["/app/nodeagent"]
